version: "3"
services:
  exim:
    image: synstd/exim:latest
    container_name: exim
    hostname: exim
    restart: unless-stopped
    user: 999:999
    ports:
      - "25:25"
      - "465:465"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./etc/exim.conf:/etc/exim/exim.conf:ro"
      - "./log:/var/log/exim"
      - "./tls:/etc/tls:ro"
