version: "3"
services:
  metabase:
    image: metabase/metabase:latest
    hostname: metabase
    container_name: metabase
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: 50m
    ports:
      - 3003:3000
    networks:
      - metanet
    environment:
      # JAVA_TIMEZONE: Europe/Moscow
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: postgres
      MB_DB_USER: $USERNAME
      MB_DB_PASS: $PASSWORD
    volumes:
      - ./data:/metabase-data
      - /dev/urandom:/dev/random:ro
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: $USERNAME
      POSTGRES_PASSWORD: $PASSWORD
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - metanet
networks:
  metanet:
    driver: bridge
