version: "3"
services:
  telegraf:
    image: telegraf:alpine
    user: telegraf:115
    hostname: telegraf
    container_name: telegraf
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: 50m
    # ports:
    # - 8125:8125
    # - 8092:8092
    # - 8094:8094
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
      HOST: $HOST
      NAME: $NAME
      INFLUX_URL: $INFLUX_URL
      INFLUX_TOK: $INFLUX_TOK
      INFLUX_ORG: $INFLUX_ORG
      INFLUX_BUCK: $INFLUX_BUCK
      PING: $PING
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostfs:ro
