version: "3"
services:
  docker-rest:
    image: nginx:alpine
    container_name: docker-rest
    hostname: docker-rest
    restart: always
    ports:
      - "88:80"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./.passwd:/etc/nginx/.passwd:ro"
      - "./ssl:/etc/nginx/ssl:ro"
      - "./www:/var/www:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
