version: "3"
services:
  influx:
    image: influxdb:2.7
    hostname: influx
    container_name: influx
    restart: unless-stopped
    environment:
      TLS_KEY: /tls/private.pem
      TLS_CERT: /tls/fullchain.pem
    logging:
      options:
        max-file: "3"
        max-size: 50m
    ports:
      - 18086:8086
    volumes:
      - ./db:/var/lib/influxdb2
      - ./etc:/etc/influxdb2
      - ./entrypoint.sh:/entrypoint.sh
      - /opt/apps/certbot/tls/private.pem:/tls/private.pem
      - /opt/apps/certbot/tls/fullchain.pem:/tls/fullchain.pem
