version: "3"
services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy
    hostname: wireguard
    container_name: wireguard
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: 50m
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      LANG: ru
      PORT: 994
      WG_HOST: $HOST
      PASSWORD: $PASSWORD
      PASSWORD_HASH: $PASSWORD_HASH
    ports:
      # 139 & 445 = SMB PORTS
      - 993:51820/udp
      - 994:994/tcp
    volumes:
      - "./config:/etc/wireguard"
