version: "3"
services:
  wireguard:
    image: weejewel/wg-easy
    hostname: wireguard
    container_name: wireguard
    restart: unless-stopped
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      WG_HOST: ${HOST}
      PASSWORD: ${PASS}
    ports:
      # 139 & 445 = SMB PORTS
      - "993:51820/udp"
      - "994:51821"
    volumes:
      - "./config:/etc/wireguard"
