version: "3"
services:
  php-fpm:
    image: synstd/php:8.1
    container_name: php-fpm
    hostname: php-fpm
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - /opt/sites:/opt/sites:rw
      - ./www-home:/var/www:rw
      - ./run/php:/run/php:rw
      - ./run/mysqld:/var/run/mysqld:rw
      - ./root/.ssh:/root/.ssh:ro
      - ./root/.bashrc:/root/.bashrc:rw
      - ./root/.bash_profile:/root/.bash_profile:rw
      - ./etc/crontabs:/var/spool/cron/crontabs:rw
