version: "3"
services:
  prometheus:
    image: prom/prometheus
    hostname: prometheus
    container_name: prometheus
    restart: unless-stopped
    logging:
      options:
        max-file: "3"
        max-size: 50m
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    ports:
      - 9090:9090
    volumes:
      # - "/opt/apps/certbot/tls/private.pem:/tls/private.pem"
      # - "/opt/apps/certbot/tls/fullchain.pem:/tls/fullchain.pem"
      - ./db:/prometheus
      - ./etc:/etc/prometheus
