version: "3"
services:
  prometheus:
    image: prom/prometheus
    hostname: "prometheus"
    container_name: prometheus
    restart: unless-stopped
    environment:
      TLS_KEY: /tls/private.pem
      TLS_CERT: /tls/fullchain.pem
    ports:
      - "9090:9090"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./db/:/root/.prometheus/"
      - "./etc:/etc/prometheus"
      - "/opt/apps/certbot/tls/private.pem:/tls/private.pem"
      - "/opt/apps/certbot/tls/fullchain.pem:/tls/fullchain.pem"
