version: "3"

services:
  base: &base
    image: chatwoot/chatwoot:$CHATWOOT_VERSION
    env_file: .env
    volumes:
      - ./data/storage:/app/storage

  rails:
    <<: *base
    external_links:
      - postgres:postgres
      - redis:redis
      # - postgres-XXXX-chat:postgres
      # - redis-XXXX-chat:redis
    depends_on:
      - postgres
    networks:
      - chatwoot
    ports:
      - "0.0.0.0:3030:3000"
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]

  sidekiq:
    depends_on:
      - postgres
    <<: *base
    external_links:
      - postgres:postgres
      - redis:redis
    networks:
      - chatwoot
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]

  postgres:
    image: postgres:15
    restart: always
    networks:
      - chatwoot
    ports:
      # - '5432:5432'
      - "0.0.0.0:5432:5432"
    volumes:
      - ./data/postgres15:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

networks:
  chatwoot:
    external: true
