services:
  influx:
    image: influxdb:alpine
    hostname: influx
    container_name: influx
    restart: unless-stopped
    environment:
      INFLUXD_TLS_KEY: /tls/private.pem
      INFLUXD_TLS_CERT: /tls/fullchain.pem
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: $USERNAME
      DOCKER_INFLUXDB_INIT_PASSWORD: $PASSWORD
      DOCKER_INFLUXDB_INIT_ORG:  $ORG
      DOCKER_INFLUXDB_INIT_BUCKET:  $BUCKET
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:  $ADMIN_TOKEN
    logging:
      options:
        max-file: "3"
        max-size: 50m
    ports:
      - 18086:8086
    volumes:
      - ./etc:/etc/influxdb2
      - ./db:/var/lib/influxdb2
      - /opt/apps/certbot/tls/private.pem:/tls/private.pem
      - /opt/apps/certbot/tls/fullchain.pem:/tls/fullchain.pem
