version: "3"
services:
  php-fpm:
    image: synstd/php:8.1
    container_name: php-fpm
    hostname: php-fpm
    restart: always
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    ports:
      - 22:15
    volumes:
      - /opt/sites:/opt/sites:rw
      - ./www-home:/var/www:rw
      - ./run/php:/run/php:rw
      - ./root/.ssh:/root/.ssh:ro
      - ./root/.bashrc:/root/.bashrc:ro
      - ./root/.bash_profile:/root/.bash_profile:ro
      - ./etc/php/www.conf:/etc/php/8.1/fpm/pool.d/www.conf:ro
      - ./etc/php/opcache.ini:/etc/php/8.1/mods-available/opcache.ini:ro
      - ./etc/cron/crontabs:/var/spool/cron/crontabs:rw
