version: "3"
services:
  docker-proxy:
    image: nginx:alpine
    container_name: docker-proxy
    hostname: docker-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-file: "3"
        max-size: "50m"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./includes:/etc/nginx/includes:ro"
      - "./default:/etc/nginx/default:ro"
      - "./vhosts:/etc/nginx/vhosts:ro"
      - "./default/www:/var/www/html:ro"
      - "/opt/sites:/opt/sites:rw"
