version: "3"
services:
  certbot:
    image: certbot/certbot
    hostname: certbot
    container_name: certbot
    # restart: always
    logging:
      options:
        max-file: "3"
        max-size: 50m
    volumes:
      - ./etc:/etc/letsencrypt
      - ./var:/var/lib/letsencrypt
      - ./log:/var/log/letsencrypt
      - ${WEBROOT}:/var/www/html
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/html
      - --register-unsafely-without-email
      - --agree-tos
      - --no-eff-email
      - --expand -d $HOSTS
      # - $HOSTS1
      # - $HOSTS2
      # - $HOSTS3
      # - $HOSTS4
